language: node_js
node_js:
  - 10
script:
  - npm run dist || travis_terminate 1
  - npm run security || travis_terminate 1
  - npm run test-publish || travis_terminate 1
cache:
  directories:
    - "node_modules"
